export const SET_CURRENT_USER = "SET_CURRENT_USER";

export const GET_QUIZZES = "GET_QUIZZES";
export const QUIZZES_LOADING = "QUIZZ_LOADING";

export const GET_TRACKS = "GET_TRACKS";
export const FILTER_BY_TRACKS = "FILTER_BY_TRACKS";
export const TRACKS_LOADING = "TRACKS_LOADING";

export const GET_PROFILE = "GET_PROFILE";
export const PROFILE_LOADING = "PROFILE_LOADING";
export const PROFILE_NOT_FOUND = "PROFILE_NOT_FOUND";
export const CLEAR_CURRENT_PROFILE = "CLEAR_CURRENT_PROFILE";

export const GET_USER = "GET_USER";
export const USER_LOADING = "USER_LOADING";

export const GET_ERRORS = "GET_ERRORS";
